name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      DEV: 'no'
      PROD: 'no'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: install pip3, awscli and boto3
      run: | 
         sudo apt-get -y python3-pip awscli
         sudo python3 -m pip install boto3
         python3 -m pip install --upgrade awscli
         
    - name: copy main.py
      run: | 
    - name: copy Terraform Python CDK main file - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |-
        cat main.py <<EOF
        EOF
