name: UNEMY-Stack-on-AWS-Lighsail

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names

jobs:
  Ubuntu-Python-Terraform-CDK-Build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      DEV: 'yes'
      PROD: 'no'
      DIFF: 'no'
      APPLY: 'no'
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #AWS_REGION: ${{ secrets.AWS_REGION }}
      #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: | 
         sudo apt -y install python3.9 python3-pip awscli
         python3 -m pip install boto3 --upgrade awscli
         sudo apt install npm
         sudo npm install -g cdktf-cli
         sudo npm install -g cdktf-cli@next
         sudo mkdir ${env.DEV}
         cd ${env.DEV}
         # store state locally for now (change backend later)
         sudo cdktf init --template="python-pip" --local
         sudo npm install -a @cdktf/provider-aws
         sudo cdktf get
         
    - name: Copy Terraform Python CDK modules - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |-
        cat main-dev.py <<EOF
        EOF
        &&
        cat startup-script.sh <<EOF
        EOF
        
    - name: Copy Terraform Python CDK modules - Prod
      if: ${{ env.PROD == 'yes' }}
      run: |-
        cat main-prod.py <<EOF
        EOF
        &&
        cat startup-script.sh <<EOF
        EOF
        
    - name: Terraform CDK Plan
      if:  (env.PLAN == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: sudo cdktf synth
      
    - name: Terraform CDK Difference
      if:  (env.DIFF == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: sudo cdktf cdktf diff
      
    - name: Terraform CDK Apply Dev
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.DEV == 'yes'
      run: sudo cdktf deploy
    
    - name: Terraform CDK Apply Prod
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.PROD == 'yes'
      run: terraform apply -var-file=prod.auto.tfvars -auto-approve
  
    - name: Terraform CDK Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: sudo cdktf destroy

    - name: Invoke Terraform Python CDK modules - Dev
      if: ${{ env.DEV == 'yes' }}
      run: python3 main.py
